package com.finance_backend.ai.expenseCategorization.dto;

public enum CategorizationSource {
    /** Came from a merchant mapping the user has already confirmed before -- no AI call made. */
    LEARNED,
    /** Freshly generated by the AI provider (Gemini or Ollama fallback). */
    AI_SUGGESTED
}
